# Generated by Django 3.0.5 on 2023-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20231128_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsciber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
    ]
