# Generated by Django 3.0.5 on 2023-11-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_subsciber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciber',
            new_name='Subscriber',
        ),
    ]
